# Generated by Django 5.2.16 on 2026-08-02 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('competition_type', models.CharField(choices=[('LEAGUE', 'League'), ('CUP', 'Cup'), ('FRIENDLY', 'Friendly'), ('TOURNAMENT', 'Tournament')], max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_competition_per_country')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/photos/')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.country')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_foot', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left'), ('BOTH', 'Both')], max_length=10)),
                ('jersey_name', models.CharField(blank=True, max_length=50)),
                ('current_height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fifa_connect_id', models.CharField(blank=True, max_length=100)),
                ('transfermarkt_id', models.CharField(blank=True, max_length=100)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='football.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_seasons', to='football.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_seasons', to='football.season')),
            ],
            options={
                'ordering': ['-season__start_date', 'competition__name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('SENIOR', 'Senior'), ('RESERVE', 'Reserve'), ('YOUTH', 'Youth'), ('WOMEN', 'Women')], max_length=30)),
                ('age_group', models.CharField(blank=True, choices=[('', 'Senior'), ('U7', 'Under 7'), ('U9', 'Under 9'), ('U11', 'Under 11'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17'), ('U20', 'Under 20'), ('U23', 'Under 23'), ('DEVELOPMENT', 'Development')], max_length=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamCompetitionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='football.competitionseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_participations', to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 = primary position')),
                ('proficiency', models.PositiveSmallIntegerField(default=100, help_text='Estimated proficiency (0-100).')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='reference.position')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='football.playerprofile')),
            ],
            options={
                'ordering': ['priority', 'position__display_order'],
                'constraints': [models.UniqueConstraint(fields=('player', 'position'), name='unique_player_position'), models.UniqueConstraint(fields=('player', 'priority'), name='unique_player_position_priority')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionseason',
            constraint=models.UniqueConstraint(fields=('competition', 'season'), name='unique_competition_season'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('category', 'age_group', 'name'), name='unique_team_per_category_and_age_group'),
        ),
        migrations.AddConstraint(
            model_name='teamcompetitionentry',
            constraint=models.UniqueConstraint(fields=('competition_season', 'team'), name='unique_team_per_competition_season'),
        ),
    ]
