# Generated by Django 5.2.16 on 2026-08-04 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_person_nationality'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('is_professional', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.organization')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='football.playerprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('squad_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('LOAN', 'Loan'), ('TRIAL', 'Trial'), ('ACADEMY', 'Academy')], default='PERMANENT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INJURED', 'Injured'), ('SUSPENDED', 'Suspended'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='organizations.organization')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='football.playerprofile')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_registrations', to='football.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='football.team')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('player', 'organization', 'team', 'season'), name='unique_player_team_season')],
            },
        ),
    ]
