# Generated by Django 5.2.16 on 2026-08-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('football', '0002_alter_person_nationality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
