# Generated by Django 5.2.16 on 2026-08-25 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0003_remove_matchevent_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('video', models.FileField(blank=True, null=True, upload_to='matches/videos/')),
                ('external_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('UPLOAD', 'Upload'), ('EXTERNAL', 'External')], default='UPLOAD', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='matches.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('start_second', models.PositiveIntegerField()),
                ('end_second', models.PositiveIntegerField()),
                ('clip', models.FileField(blank=True, null=True, upload_to='matches/clips/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_clips', to='matches.matchevent')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='videos.matchvideo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
