# Generated by Django 5.2.16 on 2026-08-02 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('line', models.CharField(choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENSE', 'Defense'), ('MIDFIELD', 'Midfield'), ('ATTACK', 'Attack')], max_length=20)),
                ('side', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
