# Generated by Django 5.2.16 on 2026-08-25 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_bodypart_eventcategory_eventoutcome_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('CV', 'Computer Vision'), ('GPS', 'GPS'), ('IMPORTED', 'Imported')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
