# Generated by Django 5.2.16 on 2026-08-04 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0003_contract_playerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('matchday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='football.team')),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='football.competitionseason')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='football.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='football.venue')),
            ],
            options={
                'ordering': ['-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shirt_number', models.PositiveSmallIntegerField()),
                ('selection_type', models.CharField(choices=[('STARTING', 'Starting XI'), ('SUBSTITUTE', 'Substitute'), ('RESERVE', 'Reserve')], default='STARTING', max_length=20)),
                ('is_captain', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match')),
                ('player_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_lineups', to='football.playerregistration')),
            ],
            options={
                'ordering': ['selection_type', 'shirt_number'],
                'constraints': [models.UniqueConstraint(fields=('match', 'player_registration'), name='unique_player_in_match_lineup')],
            },
        ),
    ]
