# Generated by Django 5.2.16 on 2026-08-12 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('reference', '0002_bodypart_eventcategory_eventoutcome_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAppearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entered_period', models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('ET1', 'Extra Time First Half'), ('ET2', 'Extra Time Second Half'), ('PEN', 'Penalty Shootout')], max_length=4)),
                ('entered_second', models.PositiveSmallIntegerField(default=0)),
                ('exited_period', models.CharField(blank=True, choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('ET1', 'Extra Time First Half'), ('ET2', 'Extra Time Second Half'), ('PEN', 'Penalty Shootout')], max_length=4, null=True)),
                ('exited_second', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_player_of_match', models.BooleanField(default=False)),
                ('lineup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to='matches.matchlineup')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_appearances', to='reference.position')),
            ],
            options={
                'ordering': ['entered_period'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period', models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('ET1', 'Extra Time First Half'), ('ET2', 'Extra Time Second Half'), ('PEN', 'Penalty Shootout')], max_length=4)),
                ('second', models.PositiveIntegerField()),
                ('x_start', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('y_start', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('x_end', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('y_end', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matches.matchappearance')),
                ('body_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reference.bodypart')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reference.eventtype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reference.eventoutcome')),
            ],
            options={
                'ordering': ['second'],
            },
        ),
        migrations.CreateModel(
            name='MatchEventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('RECEIVER', 'Receiver'), ('ASSISTER', 'Assister'), ('OPPONENT', 'Opponent'), ('OTHER', 'Other')], max_length=20)),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='matches.matchappearance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.matchevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'appearance', 'role'), name='unique_event_participant_role')],
            },
        ),
    ]
