# Generated by Django 5.2.16 on 2026-08-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchappearance_matchevent_matcheventparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='match',
        ),
    ]
