# Generated by Django 5.2.16 on 2026-08-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_matchevent_match'),
        ('reference', '0003_eventsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reference.eventsource'),
        ),
    ]
